export const clientTableContentRight = [
  {
    id: 1,
    tableRow1: "R",
    tableRow2: "Far",
    tableRow3: "Interm",
    tableRow4: "Near",
  },
  {
    id: 2,
    tableRow1: "Sph.",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
  {
    id: 3,
    tableRow1: "Cyl.",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
  {
    id: 4,
    tableRow1: "Axis",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
  {
    id: 5,
    tableRow1: "Add.",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
  {
    id: 6,
    tableRow1: "PD",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
  {
    id: 7,
    tableRow1: "HT",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
  {
    id: 8,
    tableRow1: "Prism",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
  {
    id: 9,
    tableRow1: "Base",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
  {
    id: 10,
    tableRow1: "Visc. Ac.",
    tableRow2: "",
    tableRow3: "",
    tableRow4: "",
  },
];
